"""Structured schemas for AI-generated artifacts."""

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class AssertionRule(BaseModel):
    """A single response assertion rule."""

    source: str = Field(..., min_length=1)
    property: Optional[str] = None
    operator: str = Field(..., min_length=1)
    value: Any = None
    description: Optional[str] = None


class ExtractionRule(BaseModel):
    """A single variable extraction rule."""

    var_name: str = Field(..., min_length=1)
    field: str = Field(..., min_length=1)
    description: Optional[str] = None


class TestCaseSpec(BaseModel):
    """Structured API test case generated by the model."""

    name: str = Field(..., min_length=1)
    description: Optional[str] = None
    priority: str = Field(..., min_length=1)
    request_data: Dict[str, Any] = Field(default_factory=dict)
    required_variables: List[str] = Field(default_factory=list)
    data_prep: List[str] = Field(default_factory=list)
    assertion_rules: List[AssertionRule] = Field(default_factory=list)
    extraction_rules: List[ExtractionRule] = Field(default_factory=list)
    pre_sql: Optional[str] = None
    post_sql: Optional[str] = None
    ai_confidence: Optional[float] = None

    model_config = ConfigDict(extra="allow")
