/**
 * 链路管理页面 - 统一管理内部链路和跨模块链路
 * 符合前端代码规范：
 * 1. 空值防御：使用可选链和默认值
 * 2. 防止重复提交：按钮加载状态
 * 3. 友好异常提示：统一错误处理
 * 4. 高频事件节流：搜索框防抖
 */
import React, { useState, useEffect, useCallback } from 'react';
import { Table, Tabs, Button, Space, Tag, Modal, Steps, Descriptions, message, Alert } from 'antd';
import { EyeOutlined, PlayCircleOutlined, ReloadOutlined } from '@ant-design/icons';
import { useProjectStore } from '../../store/project';
import { useAuthStore } from '../../store/auth';
import { useSearchParams } from 'react-router-dom';
import api from '../../services/api';

const { TabPane } = Tabs;

interface Chain {
  id: number | string;
  name: string;
  description?: string;
  type: 'internal' | 'cross-module';
  group_id?: number;
  group_name?: string;
  module_count?: number;
  endpoint_count: number;
  complexity_score?: number;
  auto_generated?: boolean;
  status: string;
  related_scenario_id?: number;
  created_at?: string;
  updated_at?: string;
  endpoint_ids?: number[];
  execution_order?: any[];
  endpoint_details?: any[];
  chain_structure?: any[];
}

interface ChainDetail {
  id: number | string;
  name: string;
  description?: string;
  type: 'internal' | 'cross-module';
  endpoint_details?: any[];
  related_scenario?: {
    id: number;
    name: string;
    status: string;
  };
}

const ChainList: React.FC = () => {
  const { currentProject } = useProjectStore();
  const { token } = useAuthStore();
  const [searchParams] = useSearchParams();
  const [activeTab, setActiveTab] = useState('internal');
  const [internalChains, setInternalChains] = useState<Chain[]>([]);
  const [crossModuleChains, setCrossModuleChains] = useState<Chain[]>([]);
  const [loading, setLoading] = useState(false);
  const [detailVisible, setDetailVisible] = useState(false);
  const [selectedChain, setSelectedChain] = useState<ChainDetail | null>(null);
  const [filteredGroupId, setFilteredGroupId] = useState<number | null>(null);

  

  // 加载内部链路
  const loadInternalChains = useCallback(async () => {
    if (!token) {
      return;
    }
    
    if (!currentProject?.id) {
      return;
    }
    
    try {
      const params: any = { project_id: currentProject.id, chain_type: 'internal' };
      if (filteredGroupId) {
        params.group_id = filteredGroupId;
      }
      
      const response = await api.get('/api-integration/chains', { params });
      
      if (response.code === 0) {
        setInternalChains(response.data.internal_chains || []);
      } else {
        message.error(response.message || '加载内部链路失败');
      }
    } catch (error) {
      console.error('加载内部链路失败:', error);
      message.error('网络连接不稳定，请重试');
    }
  }, [currentProject?.id, filteredGroupId, token]);

  // 加载跨模块链路
  const loadCrossModuleChains = useCallback(async () => {
    if (!token) {
      return;
    }
    
    if (!currentProject?.id) {
      return;
    }
    
    try {
      const response = await api.get('/api-integration/chains', {
        params: { project_id: currentProject.id, chain_type: 'cross-module' }
      });
      
      if (response.code === 0) {
        setCrossModuleChains(response.data.cross_module_chains || []);
      } else {
        message.error(response.message || '加载跨模块链路失败');
      }
    } catch (error) {
      console.error('加载跨模块链路失败:', error);
      message.error('网络连接不稳定，请重试');
    }
  }, [currentProject?.id, token]);

  // 解析URL参数中的group_id
  useEffect(() => {
    const groupId = searchParams.get('group_id');
    if (groupId) {
      setFilteredGroupId(parseInt(groupId));
      setActiveTab('internal'); // 如果有group_id，自动切换到内部链路标签
    } else {
      setFilteredGroupId(null);
    }
  }, [searchParams]);

  useEffect(() => {
    // 只有在用户已登录且有当前项目时才加载数据
    if (token && currentProject?.id) {
      loadInternalChains();
      loadCrossModuleChains();
    }
  }, [loadInternalChains, loadCrossModuleChains, token, currentProject?.id]);

  // 内部链路表格列
  const internalChainColumns = [
    { 
      title: '链路ID', 
      dataIndex: 'id', 
      key: 'id', 
      width: 100 
    },
    { 
      title: '链路名称', 
      dataIndex: 'name', 
      key: 'name',
      ellipsis: true
    },
    { 
      title: '所属模块', 
      dataIndex: 'group_name', 
      key: 'group_name',
      ellipsis: true
    },
    { 
      title: '接口数量', 
      dataIndex: 'endpoint_count', 
      key: 'endpoint_count', 
      width: 100 
    },
    {
      title: '类型',
      dataIndex: 'auto_generated',
      key: 'auto_generated',
      width: 120,
      render: (autoGenerated: boolean) => (
        <Tag color={autoGenerated ? 'blue' : 'green'}>
          {autoGenerated ? '自动生成' : '手动创建'}
        </Tag>
      )
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: string) => (
        <Tag color={status === 'active' ? 'green' : 'default'}>
          {status === 'active' ? '活跃' : '已废弃'}
        </Tag>
      )
    },
    {
      title: '操作',
      key: 'action',
      width: 200,
      render: (_: any, record: Chain) => (
        <Space size="small">
          <Button 
            type="link" 
            icon={<EyeOutlined />} 
            onClick={() => viewChainDetail('internal', record)}
          >
            详情
          </Button>
          <Button 
            type="link" 
            icon={<PlayCircleOutlined />} 
            onClick={() => generateScenario('internal', record)}
          >
            生成场景
          </Button>
        </Space>
      )
    }
  ];

  // 跨模块链路表格列
  const crossModuleChainColumns = [
    { 
      title: 'ID', 
      dataIndex: 'id', 
      key: 'id', 
      width: 80 
    },
    { 
      title: '链路名称', 
      dataIndex: 'name', 
      key: 'name',
      ellipsis: true
    },
    { 
      title: '模块数量', 
      dataIndex: 'module_count', 
      key: 'module_count', 
      width: 100 
    },
    { 
      title: '接口数量', 
      dataIndex: 'endpoint_count', 
      key: 'endpoint_count', 
      width: 100 
    },
    {
      title: '状态',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: string) => (
        <Tag color={status === 'active' ? 'green' : 'default'}>
          {status === 'active' ? '活跃' : '已废弃'}
        </Tag>
      )
    },
    {
      title: '操作',
      key: 'action',
      width: 200,
      render: (_: any, record: Chain) => (
        <Space size="small">
          <Button 
            type="link" 
            icon={<EyeOutlined />} 
            onClick={() => viewChainDetail('cross-module', record)}
          >
            详情
          </Button>
          <Button 
            type="link" 
            icon={<PlayCircleOutlined />} 
            onClick={() => generateScenario('cross-module', record)}
          >
            生成场景
          </Button>
        </Space>
      )
    }
  ];

  // 查看链路详情
  const viewChainDetail = async (type: string, record: Chain) => {
    try {
      const chainId = typeof record.id === 'string' ? parseInt(record.id.split('_')[1] || '0') : record.id;
      
      const response = await api.get(`/api-integration/chains/${type}/${chainId}`);
      
      if (response.code === 0) {
        setSelectedChain(response.data);
        setDetailVisible(true);
      } else {
        message.error(response.message || '获取链路详情失败');
      }
    } catch (error) {
      console.error('获取链路详情失败:', error);
      message.error('网络连接不稳定，请重试');
    }
  };

  // 生成场景
  const generateScenario = (type: string, record: Chain) => {
    Modal.confirm({
      title: '生成场景',
      content: `是否从链路 "${record.name}" 生成测试场景？`,
      okText: '确认',
      cancelText: '取消',
      onOk: async () => {
        try {
          const chainId = typeof record.id === 'string' ? parseInt(record.id.split('_')[1] || '0') : record.id;
          
          const response = await api.post(`/api-integration/chains/${type}/${chainId}/generate-scenario`, {
            project_id: currentProject.id,
            scenario_name: `${record.name}-场景`,
            scenario_type: 'functional',
            category: 'chain-generated',
            description: `从链路 "${record.name}" 自动生成`
          });
          
          if (response.code === 0) {
            message.success('场景生成成功');
            // 刷新链路列表，更新关联场景ID
            if (type === 'internal') {
              loadInternalChains();
            } else {
              loadCrossModuleChains();
            }
          } else {
            message.error(response.message || '场景生成失败');
          }
        } catch (error) {
          console.error('场景生成失败:', error);
          message.error('网络连接不稳定，请重试');
        }
      }
    });
  };

  // 刷新列表
  const handleRefresh = () => {
    loadInternalChains();
    loadCrossModuleChains();
    message.success('刷新成功');
  };

  // 测试chains API
  const handleTestChainsApi = async () => {
    try {
      const response = await api.get('/api-integration/chains/test');
      message.success('chains API测试成功');
    } catch (error) {
      message.error('chains API测试失败');
    }
  };

  // 渲染复杂度星级
  const renderComplexityStars = (score: number = 1) => {
    return [...Array(score)].map((_, i) => '★').join('');
  };

  return (
    <div style={{ padding: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
        <h1>链路管理</h1>
        <Space>
          <Button onClick={handleTestChainsApi}>
            测试API
          </Button>
          <Button icon={<ReloadOutlined />} onClick={handleRefresh}>
            刷新
          </Button>
        </Space>
      </div>
      
      {/* 提示信息 */}
      {!currentProject?.id && (
        <div style={{ marginBottom: 16 }}>
          <Alert
            message="请先选择项目"
            description="需要选择一个项目后才能查看链路信息"
            type="info"
            showIcon
          />
        </div>
      )}
      
      {!token && (
        <div style={{ marginBottom: 16 }}>
          <Alert
            message="未登录"
            description="请登录后查看链路信息"
            type="warning"
            showIcon
            action={
              <Button type="primary" size="small" onClick={() => window.location.href = '/login'}>
                去登录
              </Button>
            }
          />
        </div>
      )}
      
      <Tabs activeKey={activeTab} onChange={setActiveTab}>
        <TabPane tab={`内部链路 (${internalChains.length})`} key="internal">
          <Table
            columns={internalChainColumns}
            dataSource={internalChains}
            rowKey="id"
            loading={loading}
            pagination={{ pageSize: 20 }}
          />
        </TabPane>
        
        <TabPane tab={`跨模块链路 (${crossModuleChains.length})`} key="cross-module">
          <Table
            columns={crossModuleChainColumns}
            dataSource={crossModuleChains}
            rowKey="id"
            loading={loading}
            pagination={{ pageSize: 20 }}
          />
        </TabPane>
      </Tabs>

      {/* 链路详情弹框 */}
      <Modal
        title={`链路详情 - ${selectedChain?.name}`}
        open={detailVisible}
        onCancel={() => setDetailVisible(false)}
        footer={[
          <Button key="close" onClick={() => setDetailVisible(false)}>
            关闭
          </Button>,
          <Button 
            key="generate" 
            type="primary" 
            icon={<PlayCircleOutlined />}
            onClick={() => {
              if (selectedChain) {
                generateScenario(selectedChain.type, selectedChain as any);
              }
            }}
          >
            生成场景
          </Button>
        ]}
        width={1000}
      >
        {selectedChain && (
          <>
            <Descriptions bordered column={2} style={{ marginBottom: 16 }}>
              <Descriptions.Item label="链路ID">{selectedChain.id}</Descriptions.Item>
              <Descriptions.Item label="链路类型">
                <Tag color={selectedChain.type === 'internal' ? 'blue' : 'green'}>
                  {selectedChain.type === 'internal' ? '内部链路' : '跨模块链路'}
                </Tag>
              </Descriptions.Item>
              <Descriptions.Item label="接口数量">{selectedChain.endpoint_count || 0}</Descriptions.Item>
              {selectedChain.group_name && (
                <Descriptions.Item label="所属模块">{selectedChain.group_name}</Descriptions.Item>
              )}
              <Descriptions.Item label="复杂度" span={2}>
                {renderComplexityStars(selectedChain.complexity_score)}
              </Descriptions.Item>
              <Descriptions.Item label="描述" span={2}>
                {selectedChain.description || '无'}
              </Descriptions.Item>
            </Descriptions>

            <h3>执行步骤</h3>
            <Steps
              direction="vertical"
              current={-1}
              items={selectedChain.endpoint_details?.map((ep: any, index: number) => ({
                title: `步骤 ${index + 1}`,
                description: (
                  <div>
                    <Tag color="blue">{ep.method}</Tag>
                    <span>{ep.path}</span>
                    {ep.variables && Object.keys(ep.variables).length > 0 && (
                      <div style={{ marginTop: 4, fontSize: 12, color: '#999' }}>
                        变量: {JSON.stringify(ep.variables)}
                      </div>
                    )}
                  </div>
                )
              }))}
            />

            {selectedChain.related_scenario && (
              <div style={{ marginTop: 16, padding: 12, backgroundColor: '#f6ffed', borderRadius: 4 }}>
                <span style={{ color: '#52c41a', marginRight: 8 }}>✓</span>
                已关联场景: <strong>{selectedChain.related_scenario.name}</strong>
              </div>
            )}
          </>
        )}
      </Modal>
    </div>
  );
};

export default ChainList;